#!/usr/bin/env python3
"""Generate INDEX.md from the skill directories — the one honest catalog.

Scans <NN-category>/<skill>/SKILL.md, reads each frontmatter description and
line count, and writes INDEX.md. Run after adding, removing, or rebuilding
skills (CI should verify INDEX.md is up to date by re-running this).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATEGORY_DIR_RE = re.compile(r"^\d{2}-[a-z0-9-]+$")

CATEGORY_LABELS = {
    "01-software-dev": "Software Development",
    "02-devops-infra": "DevOps & Infrastructure",
    "03-data-analytics": "Data & Analytics",
    "04-ai-ml": "AI / ML",
    "05-security": "Security",
    "06-system-design": "System Design",
    "07-testing-quality": "Testing & Quality",
    "08-api-integration": "API & Integration",
    "09-product-management": "Product Management",
}


def first_sentence(text: str) -> str:
    m = re.search(r"^description:\s*(.+)$", text, re.M)
    if not m:
        return ""
    desc = m.group(1).strip()
    return desc.split(". ")[0].rstrip(".") + "."


def main():
    lines_out = [
        "# Tech Skills Collection — Index",
        "",
        "<!-- GENERATED by scripts/generate_index.py — do not edit by hand. -->",
        "",
    ]
    total = 0
    sections = []
    for cat_dir in sorted(p for p in ROOT.iterdir()
                          if p.is_dir() and CATEGORY_DIR_RE.match(p.name)):
        rows = []
        for f in sorted(cat_dir.glob("*/SKILL.md")):
            text = f.read_text()
            n = len(text.splitlines())
            rows.append((f.parent.name, first_sentence(text), n))
        total += len(rows)
        label = CATEGORY_LABELS.get(cat_dir.name, cat_dir.name)
        section = [f"## {label} ({len(rows)})", "",
                   "| Skill | Description | Lines |", "|---|---|---|"]
        for name, desc, n in rows:
            section.append(f"| `{cat_dir.name}/{name}` | {desc} | {n} |")
        section.append("")
        sections.append(section)

    lines_out.append(f"**Total skills in this repository: {total}** "
                     "(the live site additionally serves categories whose "
                     "sources are still being reconciled — see "
                     "`scripts/audit_skills.py`).")
    lines_out.append("")
    for s in sections:
        lines_out.extend(s)

    (ROOT / "INDEX.md").write_text("\n".join(lines_out))
    print(f"wrote INDEX.md: {total} skills")


if __name__ == "__main__":
    main()
